import{TARGET,DAYS,SWAPS,GROCERY,calories,total}from'./data.js';
const app=document.querySelector('#app'),KEY='macrocut-v1';
const DEF={start:new Date().toISOString().slice(0,10),completed:{},weights:[],grocery:{},theme:'system',view:'today'};
let s=(()=>{try{return{...DEF,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{...DEF}}})(),modal='';
const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
const dayNow=()=>{const a=new Date(s.start+'T00:00:00'),b=new Date();b.setHours(0,0,0,0);return Math.min(60,Math.max(1,Math.floor((b-a)/86400000)+1))};
const doneCount=d=>[0,1,2,3].filter(i=>s.completed[`${d}-${i}`]).length;
const applyTheme=()=>{s.theme==='system'?document.documentElement.removeAttribute('data-theme'):document.documentElement.dataset.theme=s.theme};applyTheme();
const toast=x=>{let e=document.createElement('div');e.className='toast';e.textContent=x;document.body.appendChild(e);setTimeout(()=>e.remove(),1600)};
const macro=m=>`<div class="macros"><div class="macro card"><label>Protein</label><b>${m.protein}<span> g</span></b></div><div class="macro card"><label>Carbs</label><b>${m.carbs}<span> g</span></b></div><div class="macro card"><label>Fat</label><b>${m.fat}<span> g</span></b></div><div class="macro card"><label>Calories</label><b>${calories(m)}<span> kcal</span></b></div></div>`;
const meal=(d,x,i)=>{let z=!!s.completed[`${d}-${i}`];return`<article class="meal card ${z?'done':''}"><div class="mealTop"><div><h4>${x.name}</h4><div class="sub">${x.macro.protein}P • ${x.macro.carbs}C • ${x.macro.fat}F • ${calories(x.macro)} kcal</div></div><button class="check ${z?'done':''}" data-check="${d}-${i}">${z?'✓':''}</button></div><ul class="foods">${x.foods.map(f=>`<li>${f}</li>`).join('')}</ul></article>`};
const install=()=>/iphone|ipad|ipod/i.test(navigator.userAgent)&&!(navigator.standalone||matchMedia('(display-mode:standalone)').matches)?`<div class="install card"><div style="font-size:28px">📲</div><div><h4>Install MacroCut</h4><p>Safari → Share → Add to Home Screen.</p></div></div>`:'';
const today=()=>{let d=dayNow(),x=DAYS[d-1],m=total(x),c=doneCount(d);return`<section class="hero"><div class="eyebrow">Week ${x.week} • Day ${d}</div><h2>Today’s plan</h2><p>Weigh ingredients, hit protein, and judge progress from the weekly trend.</p></section>${install()}${macro(m)}<div class="progress card"><div class="bar"><i style="width:${c*25}%"></i></div><div class="meta"><span>${c}/4 meals complete</span><span>${c*25}%</span></div></div><div class="head"><div><h3>Meals</h3><p>Tap the circle after eating.</p></div><button class="secondary" data-day="${d}">Swaps</button></div><div class="meals">${x.meals.map((q,i)=>meal(d,q,i)).join('')}</div><div class="notice" style="margin-top:14px">Macro values are estimates. Food labels, raw/cooked weight and cooking oil determine the actual numbers.</div>`};
const plan=()=>{let c=dayNow();return`<section class="hero"><div class="eyebrow">60 days</div><h2>Your cut calendar</h2><p>Preview any day and track meal adherence.</p></section><div class="days">${DAYS.map(d=>`<button class="day ${d.day===c?'current':''}" data-day="${d.day}"><b>Day ${d.day}</b><small>Week ${d.week}</small><em>${doneCount(d.day)}/4 done</em></button>`).join('')}</div>`};
const roll=a=>a.map((x,i)=>({...x,avg:a.slice(Math.max(0,i-6),i+1).reduce((n,v)=>n+v.kg,0)/Math.min(7,i+1)}));
const chart=()=>{let a=roll([...s.weights].sort((a,b)=>a.date.localeCompare(b.date)));if(a.length<2)return'<div class="empty">Add at least 2 weigh-ins to see your trend.</div>';let w=700,h=220,p=28,vs=a.flatMap(x=>[x.kg,x.avg]),mn=Math.min(...vs)-.5,mx=Math.max(...vs)+.5,X=i=>p+i*(w-2*p)/(a.length-1),Y=v=>h-p-(v-mn)*(h-2*p)/(mx-mn||1),path=k=>a.map((x,i)=>`${i?'L':'M'}${X(i).toFixed(1)},${Y(x[k]).toFixed(1)}`).join(' ');return`<svg viewBox="0 0 ${w} ${h}" class="chart"><path d="${path('kg')}" fill="none" stroke="var(--a)" stroke-width="3"/><path d="${path('avg')}" fill="none" stroke="var(--t)" stroke-opacity=".65" stroke-width="2"/>${a.map((x,i)=>`<circle cx="${X(i)}" cy="${Y(x.kg)}" r="3" fill="var(--a)"/>`).join('')}</svg><div class="meta"><span>Green: daily</span><span>Secondary line: 7-entry average</span></div>`};
const weight=()=>{let a=[...s.weights].sort((a,b)=>a.date.localeCompare(b.date)),latest=a.at(-1)?.kg,delta=a.length?latest-a[0].kg:null,days=a.length>1?Math.max(1,(new Date(a.at(-1).date)-new Date(a[0].date))/86400000):0,pace=days?delta/(days/7):null,fmt=v=>v==null?'—':`${v>0?'+':''}${v.toFixed(1)}`;return`<section class="hero"><div class="eyebrow">Trend, not noise</div><h2>Weight progress</h2><p>Use the same scale at the same time under similar conditions.</p></section><div class="stats"><div class="stat card"><small>Latest</small><strong>${latest?.toFixed(1)||'—'}</strong><small>kg</small></div><div class="stat card"><small>Total</small><strong>${fmt(delta)}</strong><small>kg</small></div><div class="stat card"><small>Pace</small><strong>${pace==null?'—':fmt(pace)}</strong><small>kg/week</small></div><div class="stat card"><small>Entries</small><strong>${a.length}</strong><small>weigh-ins</small></div></div><div class="form card" style="margin-top:12px"><div class="row"><div class="field"><label>Date</label><input id="wd" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Weight kg</label><input id="wk" type="number" step=".1" min="20" max="400" placeholder="104.6"></div></div><button class="primary" id="addw">Add weigh-in</button></div><div class="head"><div><h3>7-entry trend</h3></div></div><div class="chartbox card">${chart()}</div><div class="head"><div><h3>History</h3></div></div><div class="card">${a.length?`<table class="table"><tbody>${[...a].reverse().slice(0,30).map(r=>`<tr><td>${r.date}</td><td><b>${r.kg.toFixed(1)} kg</b></td><td><button class="secondary" data-delw="${r.id}">Delete</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No weight entries yet.</div>'}</div>`};
const grocery=()=>{let sec=(t,k,a)=>`<div class="gro card"><h4>${t}</h4>${a.map((x,i)=>{let id=`${k}-${i}`,z=s.grocery[id];return`<label class="gitem"><input type="checkbox" data-g="${id}" ${z?'checked':''}><span style="${z?'text-decoration:line-through;opacity:.55':''}">${x[0]}</span><span class="qty">${x[1]}</span></label>`}).join('')}</div>`;return`<section class="hero"><div class="eyebrow">Weekly prep</div><h2>Grocery list</h2><p>Approximate one-person quantities. Fine-tune them against the exact week you choose.</p></section><div class="meals">${sec('Protein','p',GROCERY.protein)}${sec('Produce','v',GROCERY.produce)}${sec('Pantry','x',GROCERY.pantry)}</div><button class="secondary" id="rg" style="margin-top:12px">Reset checklist</button>`};
const settings=()=>`<section class="hero"><div class="eyebrow">Configuration</div><h2>Settings</h2><p>Everything is stored locally on this device.</p></section><div class="form card"><div class="field"><label>Plan start date</label><input id="start" type="date" value="${s.start}"></div><div class="field"><label>Appearance</label><select id="theme"><option value="system" ${s.theme==='system'?'selected':''}>System</option><option value="light" ${s.theme==='light'?'selected':''}>Light</option><option value="dark" ${s.theme==='dark'?'selected':''}>Dark</option></select></div></div><div class="head"><div><h3>Macro target</h3></div></div>${macro(TARGET)}<div class="notice"><b>Math check:</b> 170 g protein + 80 g carbs + 50 g fat = <b>1,450 kcal</b>.</div><div class="head"><div><h3>Backup</h3><p>Recommended before clearing Safari data.</p></div></div><div class="form card"><div class="row"><button class="secondary" id="export">Export JSON</button><button class="secondary" id="import">Import JSON</button></div><input id="file" type="file" accept="application/json" hidden></div><div class="head"><div><h3>Reset</h3></div></div><div class="form card"><button class="danger" id="reset">Reset all local data</button></div><div class="notice" style="margin-top:12px">MacroCut is a meal-planning and tracking tool, not medical advice.</div>`;
const openDay=n=>{let d=DAYS[n-1];modal=`<div class="modalbg" data-close><div class="modal" onclick="event.stopPropagation()"><div class="modalhead"><div><div class="eyebrow">Week ${d.week}</div><h3>Day ${n}</h3></div><button class="icon" data-close>×</button></div>${macro(total(d))}<div class="meals">${d.meals.map((x,i)=>meal(n,x,i)).join('')}</div><div class="head"><div><h3>Simple swaps</h3></div></div>${SWAPS.map(x=>`<div class="swap"><b>${x[0]}</b><div class="muted">Swap with ${x.slice(1).join(' or ')}</div></div>`).join('')}</div></div>`;render()};
function render(){let content={today,plan,weight,grocery,settings}[s.view]();let nav=[['today','⌂','Today'],['plan','▦','Plan'],['weight','↗','Weight'],['grocery','✓','Grocery'],['settings','⚙','Settings']];app.innerHTML=`<main class="shell"><header class="top"><div class="brand"><div class="logo">M</div><div><h1>MacroCut</h1><small>60-day cut</small></div></div><button class="icon" id="quick">◐</button></header>${content}</main><nav class="nav"><div class="navin">${nav.map(n=>`<button data-view="${n[0]}" class="${s.view===n[0]?'active':''}"><span>${n[1]}</span>${n[2]}</button>`).join('')}</div></nav>${modal}`;bind()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{s.view=b.dataset.view;modal='';save();render();scrollTo(0,0)});document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{s.completed[b.dataset.check]=!s.completed[b.dataset.check];save();render()});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>openDay(+b.dataset.day));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{modal='';render()});document.querySelector('#quick').onclick=()=>{s.theme=s.theme==='dark'?'light':'dark';applyTheme();save();render()};let add=document.querySelector('#addw');if(add)add.onclick=()=>{let kg=+document.querySelector('#wk').value,date=document.querySelector('#wd').value;if(!kg||kg<20||kg>400)return toast('Enter a valid weight');let e=s.weights.find(x=>x.date===date);e?e.kg=kg:s.weights.push({id:crypto.randomUUID(),date,kg});save();render();toast('Weight saved')};document.querySelectorAll('[data-delw]').forEach(b=>b.onclick=()=>{s.weights=s.weights.filter(x=>x.id!==b.dataset.delw);save();render()});document.querySelectorAll('[data-g]').forEach(x=>x.onchange=()=>{s.grocery[x.dataset.g]=x.checked;save();render()});let rg=document.querySelector('#rg');if(rg)rg.onclick=()=>{s.grocery={};save();render()};let st=document.querySelector('#start');if(st)st.onchange=()=>{s.start=st.value;save();toast('Start date updated')};let th=document.querySelector('#theme');if(th)th.onchange=()=>{s.theme=th.value;applyTheme();save();render()};let ex=document.querySelector('#export');if(ex)ex.onclick=()=>{let u=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='macrocut-backup.json';a.click();URL.revokeObjectURL(u)};let im=document.querySelector('#import'),fi=document.querySelector('#file');if(im)im.onclick=()=>fi.click();if(fi)fi.onchange=async()=>{try{s={...DEF,...JSON.parse(await fi.files[0].text())};save();applyTheme();render();toast('Backup imported')}catch{toast('Invalid backup')}};let re=document.querySelector('#reset');if(re)re.onclick=()=>{if(confirm('Reset all MacroCut data?')){s={...DEF};save();render()}}}
render();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
